<?php $this->layout('layout::default', ['title' => 'Apply style']) ?>

<?php $this->push('stylesheets') ?>
<link type="text/css" rel="stylesheet" href="/assets/css/pages/component.css">
<?php $this->end() ?>

<a href="#top" class="text-muted back-to-top"><em class="fa fa-toggle-up"></em>&nbsp;Back to top</a>
<div class="content">
    <div itemtype="http://schema.org/SoftwareSourceCode">
        <main>
            <div class="px-3">
                <div class="container-fluid">
                    <div class="row">
                        <?= $this->insert('app::nav') ?>
                        <div class="repository-content content">
                            <div class="Box Box--condensed">
                                <div class="Box-body p-5">
                                    <article class="markdown-body container-lg" itemprop="text">
                                        <h1>
                                            <a id="apply-style" class="anchor" aria-hidden="true" href="#apply-style">
                                                <svg class="octicon octicon-link" viewBox="0 0 16 16" width="16" height="16" aria-hidden="true">
                                                    <path fill-rule="evenodd" d="M4 9h1v1H4c-1.5 0-3-1.69-3-3.5S2.55 3 4 3h4c1.45 0 3 1.69 3 3.5 0 1.41-.91 2.72-2 3.25V8.59c.58-.45 1-1.27 1-2.09C10 5.22 8.98 4 8 4H4c-.98 0-2 1.22-2 2.5S3 9 4 9zm9-3h-1v1h1c1 0 2 1.22 2 2.5S13.98 12 13 12H9c-.98 0-2-1.22-2-2.5 0-.83.42-1.64 1-2.09V6.25c-1.09.53-2 1.84-2 3.25C6 11.31 7.55 13 9 13h4c1.45 0 3-1.69 3-3.5S14.5 6 13 6z"></path>
                                                </svg>
                                            </a>
                                            3. Apply style
                                        </h1>
                                        <article class="card col-12 offset-sm-2 offset-md-2 offset-lg-3 offset-xl-4">
                                            <header class="card__header">
                                                <div>
                                                    <div class="card__header__title">
                                                        Avengers: Infinity War
                                                    </div>
                                                    <div class="card__header__duration">
                                                        156 minutes
                                                    </div>
                                                </div>
                                                <div class="card__header__score">
                                                    85% <img class="icon-img" src="https://www.rottentomatoes.com/assets/pizza-pie/images/icons/global/cf-lg.3c29eff04f2.png" alt="">
                                                </div>
                                            </header>
                                            <div class="card__picture card__picture-img-gradient">
                                                <img class="card__picture-img" src="https://i.ibb.co/9tLcR7s/avengers.jpg" alt="avengers">
                                                <a  class="button" href="https://www.rottentomatoes.com/m/avengers_infinity_war" target="_blank">
                                                    Check review
                                                </a>
                                            </div>
                                            <footer>
                                                <p class="card__description">
                                                    An unprecedented cinematic journey ten years in the making and spanning the entire Marvel Cinematic Universe, Marvel Studios' "Avengers: Infinity War" brings to the screen the ultimate, deadliest showdown of all time. The Avengers and their Super Hero allies must be willing to sacrifice all in an attempt to defeat the powerful Thanos before his blitz of devastation and ruin puts an end to the universe.
                                                </p>
                                            </footer>
                                        </article>
                                    </article>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </main>
    </div>
</div>
