<nav>
    <div class="resource-group">
        <div class="heading">
            <div class="chevron"><em class="open fa fa-angle-down"></em></div>
            <a href="#top">Content</a>
        </div>
        <div class="collapse-content">
            <ul>
                <li>
                    <a href="/">Home</a>
                </li>
                <li>
                    <a href="/cache-function.php">1. Cache function</a>
                </li>
                <li>
                    <a href="/date-format.php">2. Date formatting</a>
                </li>
                <li>
                    <a href="/apply-style.php">3. Apply style</a>
                </li>
                <li>
                    <a href="/coverage.php">Test coverage</a>
                </li>
            </ul>
        </div>
    </div>
    <p style="text-align: center; word-wrap: break-word;">
        <a href="https://www.wiley.com" target="_blank" rel="noopener">https://www.wiley.com</a>
    </p>
</nav>
