<?php $this->layout('layout::default', ['title' => sprintf('%d %s', $status ?? 0, $reason ?? '')]) ?>

<a href="#top" class="text-muted back-to-top"><i class="fa fa-toggle-up"></i>&nbsp;Back to top</a>
<div class="content">
    <div itemtype="http://schema.org/SoftwareSourceCode">
        <main>
            <div class="px-3">
                <div class="container-fluid">
                    <div class="row">
                        <?= $this->insert('app::nav') ?>
                        <div class="repository-content content">
                            <div class="Box Box--condensed">
                                <div class="Box-body p-5">
                                    <article class="markdown-body container-lg" itemprop="text">
                                        <h1>
                                            <a id="error" class="anchor" aria-hidden="true" href="#error">
                                                <svg class="octicon octicon-link" viewBox="0 0 16 16" width="16" height="16" aria-hidden="true">
                                                    <path fill-rule="evenodd" d="M4 9h1v1H4c-1.5 0-3-1.69-3-3.5S2.55 3 4 3h4c1.45 0 3 1.69 3 3.5 0 1.41-.91 2.72-2 3.25V8.59c.58-.45 1-1.27 1-2.09C10 5.22 8.98 4 8 4H4c-.98 0-2 1.22-2 2.5S3 9 4 9zm9-3h-1v1h1c1 0 2 1.22 2 2.5S13.98 12 13 12H9c-.98 0-2-1.22-2-2.5 0-.83.42-1.64 1-2.09V6.25c-1.09.53-2 1.84-2 3.25C6 11.31 7.55 13 9 13h4c1.45 0 3-1.69 3-3.5S14.5 6 13 6z"></path>
                                                </svg>
                                            </a>
                                            Oops!
                                        </h1>
                                        <h2>This is awkward.</h2>
                                        <p>We encountered a <?= $this->e($status) ?> <?= $this->e($reason ?? '') ?> error.</p>
                                        <?php if ($status == 404) : ?>
                                            <p> You are looking for something that doesn't exist or may have moved. Check out one of the links on this page or head back to
                                                <a href="/">Home</a>
                                                . </p>
                                        <?php endif; ?>
                                    </article>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </main>
    </div>
</div>
